# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160711_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
